version: '3.8'
services:
  db_rentx:
    image: postgres
    container_name: db_rentx
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rentx
    env_file: .env
    ports:
      - '3333:3333'
    depends_on:
      - db_ignite

volumes:
  pgdata: