version: "3.9"

services:
  db_rentx:
    image: postgres
    container_name: db_rentx
    restart: always
    ports: 
      - 5433:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - db_rentx
    depends_on:
      - db_rentx

volumes:
  pgdata: